# -*- coding: utf-8 -*-
"""StockAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Iy7HTEZJbyRDYV8QRKuSaMoR1HHCRDK
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

!pip install pandas-datareader

def get_sp500_tickers():
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    table = pd.read_html(url)[0]  # Read the first table on the page
    tickers = table["Symbol"].tolist()
    return tickers

# Fetch S&P 500 tickers
sp500_tickers = get_sp500_tickers()
print(f"Retrieved {len(sp500_tickers)} S&P 500 tickers.")

def get_top_10_companies(tickers):
    data = []
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            info = stock.info
            data.append({
                "Ticker": ticker,
                "Company Name": info.get("longName", "N/A"),
                "Market Cap": info.get("marketCap", 0),
            })
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")
            continue

    # Create DataFrame and sort by Market Cap
    df = pd.DataFrame(data)
    df = df[df["Market Cap"] > 0]  # Remove invalid data
    df = df.sort_values(by="Market Cap", ascending=False).head(10)  # Top 10
    return df

# Fetch S&P 500 tickers
sp500_tickers = get_sp500_tickers()

# Get the top 10 companies
top_10_companies = get_top_10_companies(sp500_tickers)
print(top_10_companies)

top_10_companies

def fetch_fundamentals(tickers):
    fundamentals_data = []
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            info = stock.info
            fundamentals_data.append({
                "Ticker": ticker,
                "Company Name": info.get("longName", "N/A"),
                "Sector": info.get("sector", "N/A"),
                "Industry": info.get("industry", "N/A"),
                "Market Cap": info.get("marketCap", "N/A"),
                "PE Ratio": info.get("trailingPE", "N/A"),
                "Dividend Yield": info.get("dividendYield", "N/A"),
                "52 Week High": info.get("fiftyTwoWeekHigh", "N/A"),
                "52 Week Low": info.get("fiftyTwoWeekLow", "N/A"),
                "Current Price": info.get("currentPrice", "N/A"),
            })
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")
            continue

    # Convert to DataFrame
    return pd.DataFrame(fundamentals_data)

# Get tickers of the top 10 companies
top_10_tickers = top_10_companies["Ticker"].tolist()

# Fetch fundamentals for these companies
fundamentals = fetch_fundamentals(top_10_tickers)
print(fundamentals)

fundamentals

"""## All the Fundamentals"""

def fetch_all_fundamentals(tickers):
    fundamentals_data = []
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            info = stock.info  # Fetch all fundamentals as a dictionary

            # Append the entire info dictionary
            fundamentals_data.append({"Ticker": ticker, **info})

        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")
            continue

    # Convert to DataFrame
    return pd.DataFrame(fundamentals_data)

all_fundamentals = fetch_all_fundamentals(top_10_tickers)

all_fundamentals.columns

all_fundamentals

